### ISSUE TITLE
Dúvidas sobre os parametros

### ISSUE THREAD

**Issue by wmenezes2020** [cleitonleonel/pypix#1]
pix.set_key('b5fe1edc-d108-410f-b966-eccaaca75e4f') => O que seria e onde conseguir essa informação?
pix.set_identification('123') => O que seria e onde conseguir essa informação?
pix.set_zipcode_receiver('29148613') => O que seria e onde conseguir essa informação? Seria o CEP da pessoa?...

..

**Comment by cleitonleonel** [comment]
> pix.set_key('b5fe1edc-d108-410f-b966-eccaaca75e4f') => O que seria e onde conseguir essa informação?
> pix.set_identification('123') => O que seria e onde conseguir essa informação?
> pix.set_zipcode_receiver('29148613') => O que seria e onde conseguir essa informação? Seria o CEP da pessoa?...
> 
> ..

Boas, sinto por não documentar adequadamente os campos citados, mas vamos ao que interessa.
o parâmetro 'set_key' corresponde a sua chave pix, nesse exemplo deixei uma das minhas chaves aleatórias, pois bem vc pode especificar outro tipo de chave nesse campo, como cpf, celular, e-mail ...
Já o campo 'set_identification' é como o próprio nome diz uma forma de identificar a transação, mas não serve para checar pagamentos é apenas para efeito visual e informativo do lado do pagador, então como especificado pelo BACEN esse campo se resume como um 'Identificador ou código de autenticidade de pagamento'.
Por fim o campo zipcode é como vc bem observou um campo para código postal do recebedor ou seja, seu CEP.

Espero ter conseguido esclarecer um pouco, também estou tentando entender ainda o funcionamento e as configurações do Pix então para maiores informações consulte o manual do pix junto ao BACEN, ou no próprio perfil deles aqui no github https://github.com/bacen/pix-api ...
